language: java
jdk:
- oraclejdk8

before_script:
- if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi

script:
- mvn clean install

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: 1Dl8NUihtqSSq1k8k+nDP4gjKDdMcVrXve3+wpb7VJ7leAVMKNMocZXXKukQ3pUhacrL6Tmux1M74Ypm8/juMEztPNANPyOzDG0fvb4fzSXBYXbd2YYRJLR0ulW8RY0eW6S7/zKxFArCslUnz+YG2dr6AoKA1eld9IHROQ3DwOBBhFZrflja8LbDSnmXJMxAxTlxxs+iC1qRCDXSN9qzO7LiyNdo8XjER9KSsx4uhty1E5nj9ha2OIR/tbqKEe7GflFt42M/hO2gp2msSBk9ESnq3fuIE25qdVwbqh1fZ1QKDBWoZ3ulBVfa6n5b3hn6fVwotMHW2lFJ+r2T2FuLjfO6Fqpzw0YstphHSv4r2agsjqZhxd5XJjysAMmM9UUuNC7vJi0u9jlAR6Yl8Z/tP//z+VJTrDQw7G9ppP5lMu16sVocMCefftPL6R/AP7plIVITkYZNioxX926rQofkgPVIsUTYTBP0nDIWwaZ65pOHIn0wiaPJaLNWpjbnsjPMKNJH0d9piNaz4WdhBLLWgY+WBRbhVFlV8esTPOFmkKPM96KQf5Eh2v4ne+m7kOZx/P0fG+6MeoMFNr/zE3S6qJIPJMwrMp+/uGNmDwA9K8sQGbZDpAB2AM/4+8nxX3in7QXKOHLiMAYrML/+c5xrTWXeNTpAtR8D+G1H4PDyo+I=
  file_glob: true
  file:
    - "**/target/*.jar"
  skip_cleanup: true
  on:
    tags: true
