info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@
      buildDetails: '@versionName@'

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  server:
    port: 9011

server:
  port: 9010
  server-header: "@project.name@ v@project.version@"

spring:
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
  thymeleaf:
    cache: false
    mode: HTML

---

management:
  server:
    port: 9001

server:
  port: 8080

spring:
  profiles: PROD
  thymeleaf:
    cache: true